### ISSUE TITLE
Library dependencies info request

### ISSUE THREAD

**Issue by hpsaturn** [shabaz123/starmap#2]
Hi, I'm trying to run your project example but one library is confused for me, the Teseo.h. Maybe can you share me the link of this library? Thanks in advance

**Comment by shabaz123** [comment]
Hello, that's a library here: https://github.com/shabaz123/teseo_iii_gnss
It is used with a Teseo III GPS receiver board. If a different GPS receiver board is being used, then the Teseo library and Teseo.h file doesn't need to be included, and the code would need to be adapted to use the different GPS module. Alternatively, no GPS module needs to be used if the lat/lon and time is hard-coded (or some other real-time clock or RTC library is used). I guess the code could #ifdef out the Teseo code for those who are not using it. It's an excellent GPS receiver, but I don't know what ready-made board is out there. It can be DIY'd though. More info on that and PCB files etc are at https://community.element14.com/challenges-projects/project14/timeandspace/a/timeandspace-projects/PR46/fun-with-arduino-global-navigation-satellite-systems-gnss-and-teseo-iii 

The StarmapTest example doesn't include in the Teseo library, but that test example is very minimal, it expects the user to write a few lines of code for their desired TFT of choice (or they could copy that from the StarmapProject if they are using the same TFT screen as I did). The StarmapProject is the more full example (that was the code in the demo video), and that code uses the Teseo GPS receiver, and the add-on Flash memory chip. More info on that is here: https://community.element14.com/challenges-projects/project14/timeandspace/a/timeandspace-projects/PR51/starmap-charting-the-stars-with-arduino

**Comment by hpsaturn** [comment]
Thanks for your quickly information, with that I did a new PR #3 , only for now to test the basic example.
